GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvZW1pZSIsImlkIjoiNjFkNmY1MDU2MzdkMTRhODY1YWNlYTcyIiwiaWF0IjoxNjQyMzY2MzYzfQ.ISkJr8LtY3tvFW079wP3gQJcSqvP9jegEl7sEHl0nqs

{
  "title":"Nieuwe blog4",
  "author":"Peteer Paas",
  "url":"https://example.com/test2",
  "likes": 7
}
###
DELETE http://localhost:3003/api/blogs/61e4a05d66370606719b75f7
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InR3ZWVkZWdlYnJ1aWtlciIsImlkIjoiNjFlNGEwOWU2NjM3MDYwNjcxOWI3NWZjIiwiaWF0IjoxNjQyMzczMzA0fQ.7MdvgMMKiyi6FYUEt-f1VYUc5cBdDTYTaKhfBM9ca5U
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title":"HCEsH",
  "author":"Peteer Paas",
  "likes": 7
}
###
get http://localhost:3003/api/users
###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username":"toemie",
  "name":"Tama",
  "password": "unbreakable"
}
###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username":"tweedegebruiker",
  "name":"Joris",
  "password": "nogslimmer"
}
###
POST http://localhost:3003/api/login
content-type: application/json

{
  "username":"tweedegebruiker",
  "password":"nogslimmer"
}