GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title":"Nieuwe blog2",
  "author":"Peteer Paas",
  "url":"https://example.com/test2",
  "likes": 7
}
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title":"HCEsH",
  "author":"Peteer Paas",
  "likes": 7
}
###
get http://localhost:3003/api/users
###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username":"toemie",
  "name":"Tama",
  "password": "unbreakable"
}
###
POST http://localhost:3003/api/login
content-type: application/json

{
  "username":"toemie",
  "password":"unbreakable"
}